-- Adds the two 30-day operational assessment workbooks to the live dashboard.
alter table public.control_records drop constraint if exists control_records_type_check;
alter table public.control_records add constraint control_records_type_check
  check(type in('plan','action','risk','assessment','qbo','finance','procurement'));

alter table public.control_records add column if not exists area text not null default '';
alter table public.control_records add column if not exists evidence_check text not null default '';
alter table public.control_records add column if not exists target_rating numeric(3,1) not null default 5 check(target_rating between 0 and 5);
alter table public.control_records add column if not exists domain_weight numeric(5,4) not null default 0;
alter table public.control_records add column if not exists assessed boolean not null default false;
alter table public.control_records add column if not exists finding text not null default '';
alter table public.control_records add column if not exists corrective_action text not null default '';
alter table public.control_records add column if not exists target_date date;
alter table public.control_records add column if not exists critical_control boolean not null default false;
alter table public.control_records add column if not exists review_notes text not null default '';

insert into public.control_records
  (type,code,title,domain,area,evidence_check,target_rating,domain_weight,critical_control)
values
('finance','1.1','Are monthly P&L, Balance Sheet and Cash Flow statements produced consistently?','Finance & Cash Management','Financial Visibility','Monthly financial statements; last 6–12 months',5,0.15,'No'),
('finance','1.2','Are monthly financial statements completed within 10 business days after month-end?','Finance & Cash Management','Financial Visibility','Closing calendar; actual release dates',4,0.15,'No'),
('finance','1.3','Can management determine the current cash position at any time?','Finance & Cash Management','Financial Visibility','Bank balances; cash dashboard',5,0.15,'Yes'),
('finance','1.4','Is revenue reported by customer, project and business line?','Finance & Cash Management','Financial Visibility','Revenue reports',4,0.15,'No'),
('finance','1.5','Can management determine gross profit/margin by project?','Finance & Cash Management','Financial Visibility','Project costing; project P&L',5,0.15,'Yes'),
('finance','1.6','Are actual financial results compared against budget/forecast monthly?','Finance & Cash Management','Financial Visibility','Budget-versus-actual report',4,0.15,'No'),
('finance','1.7','Is there a rolling cash-flow forecast covering at least 13 weeks?','Finance & Cash Management','Cash Management','13-week cash forecast',5,0.15,'Yes'),
('finance','1.8','Are expected customer collections incorporated into cash forecasting?','Finance & Cash Management','Cash Management','Collection forecast linked to cash forecast',5,0.15,'Yes'),
('finance','1.9','Are expected supplier, payroll and tax payments incorporated into cash forecasting?','Finance & Cash Management','Cash Management','AP and payment schedule linked to cash forecast',5,0.15,'Yes'),
('finance','1.10','Is minimum operating cash/reserve formally defined?','Finance & Cash Management','Cash Management','Treasury or cash policy',4,0.15,'No'),
('finance','1.11','Are cash shortages identified weeks in advance rather than when payments fall due?','Finance & Cash Management','Cash Management','Forecast accuracy; cash shortfall history',5,0.15,'No'),
('finance','1.12','Is excess cash deliberately managed rather than left unmanaged?','Finance & Cash Management','Cash Management','Treasury practices; placement decisions',4,0.15,'No'),
('finance','1.13','Are all company bank accounts formally documented and reconciled monthly?','Finance & Cash Management','Banking & Treasury Controls','Bank account list; monthly reconciliations',5,0.15,'Yes'),
('finance','1.14','Are bank reconciliations reviewed independently?','Finance & Cash Management','Banking & Treasury Controls','Signed reconciliation; reviewer evidence',5,0.15,'Yes'),
('finance','1.15','Are maker/checker controls used for electronic payments?','Finance & Cash Management','Banking & Treasury Controls','Online banking roles and authority',5,0.15,'Yes'),
('finance','1.16','Are bank signatories and approval limits formally documented?','Finance & Cash Management','Banking & Treasury Controls','Owner/board authorization; bank mandates',5,0.15,'No'),
('finance','1.17','Are company and personal/owner transactions clearly separated?','Finance & Cash Management','Banking & Treasury Controls','General ledger and bank transaction samples',5,0.15,'Yes'),
('finance','1.18','Is there an approved annual operating and capital budget?','Finance & Cash Management','Budget & Expense Control','Approved annual budget',4,0.15,'No'),
('finance','1.19','Are expenses tracked against approved budgets?','Finance & Cash Management','Budget & Expense Control','Budget variance report',4,0.15,'No'),
('finance','1.20','Are material variances investigated and explained?','Finance & Cash Management','Budget & Expense Control','Monthly management review; variance commentary',4,0.15,'No'),
('finance','1.21','Are expense approval limits formally established?','Finance & Cash Management','Budget & Expense Control','Delegation of Authority',5,0.15,'Yes'),
('finance','1.22','Are employee cash advances liquidated within a defined period?','Finance & Cash Management','Budget & Expense Control','Cash advances aging; liquidation policy',5,0.15,'No'),
('finance','1.23','Are company credit cards and petty cash subject to documented controls?','Finance & Cash Management','Budget & Expense Control','Policy; reconciliation; transaction samples',5,0.15,'No'),
('finance','1.24','Is AP aging available and accurate?','Finance & Cash Management','Payables & Working Capital','AP aging and reconciliation',5,0.15,'No'),
('finance','1.25','Are supplier payments scheduled based on due date and cash priorities?','Finance & Cash Management','Payables & Working Capital','Payment schedule',5,0.15,'No'),
('finance','1.26','Are supplier credit terms actively negotiated and optimized?','Finance & Cash Management','Payables & Working Capital','Vendor contracts and payment terms',4,0.15,'No'),
('finance','1.27','Are supplier advances tracked and liquidated/reconciled?','Finance & Cash Management','Payables & Working Capital','Supplier advances ledger',5,0.15,'No'),
('finance','1.28','Is working capital—AR + inventory − AP—monitored regularly?','Finance & Cash Management','Payables & Working Capital','Working-capital dashboard',4,0.15,'No'),
('finance','1.29','Is the General Ledger reconciled with subsidiary ledgers monthly?','Finance & Cash Management','Accounting Integrity & Compliance','GL-to-subsidiary ledger reconciliation',5,0.15,'Yes'),
('finance','1.30','Are taxes, statutory obligations and government remittances monitored against due dates?','Finance & Cash Management','Accounting Integrity & Compliance','Tax and compliance calendar',5,0.15,'Yes'),
('finance','1.31','Are unusual or manual journal entries reviewed and approved?','Finance & Cash Management','Accounting Integrity & Compliance','Journal-entry controls and samples',5,0.15,'No'),
('finance','1.32','Are related-party and owner transactions properly documented?','Finance & Cash Management','Accounting Integrity & Compliance','GL entries; contracts; supporting documents',5,0.15,'No'),
('finance','1.33','Are external accountant/auditor findings tracked until resolved?','Finance & Cash Management','Accounting Integrity & Compliance','Audit findings tracker',4,0.15,'No'),
('finance','1.34','Does management receive a monthly financial management pack?','Finance & Cash Management','Management Decision Support','Monthly management report',5,0.15,'No'),
('finance','1.35','Does it show Revenue, Gross Margin, EBITDA/profit, Cash, AR, AP and Working Capital?','Finance & Cash Management','Management Decision Support','Dashboard or management pack',5,0.15,'No'),
('finance','1.36','Are financial KPIs reviewed in a formal monthly management meeting?','Finance & Cash Management','Management Decision Support','Meeting minutes and action log',4,0.15,'No'),
('finance','2.1','Is there one complete and reliable AR master list?','AR, Billing & Collections','AR Accuracy & Visibility','AR aging and subledger',5,0.12,'Yes'),
('finance','2.2','Does AR reconcile to the General Ledger?','AR, Billing & Collections','AR Accuracy & Visibility','AR-to-GL reconciliation',5,0.12,'Yes'),
('finance','2.3','Is AR aging produced at least monthly?','AR, Billing & Collections','AR Accuracy & Visibility','Aging reports',5,0.12,'No'),
('finance','2.4','Is AR classified into Current, 31–60, 61–90, 91–180 and >180 days?','AR, Billing & Collections','AR Accuracy & Visibility','AR aging buckets',5,0.12,'No'),
('finance','2.5','Can AR be analyzed by customer, project and account owner?','AR, Billing & Collections','AR Accuracy & Visibility','AR analysis report',5,0.12,'No'),
('finance','2.6','Are disputed and potentially uncollectible accounts separately identified?','AR, Billing & Collections','AR Accuracy & Visibility','AR classification and exception list',5,0.12,'No'),
('finance','2.7','Does every project have a signed contract, PO or NOA before execution?','AR, Billing & Collections','Contract-to-Billing Controls','Contract files and project samples',5,0.12,'No'),
('finance','2.8','Are billing milestones clearly defined before project commencement?','AR, Billing & Collections','Contract-to-Billing Controls','Contract or PO billing terms',5,0.12,'No'),
('finance','2.9','Is responsibility for triggering billing clearly assigned?','AR, Billing & Collections','Contract-to-Billing Controls','Process map and RACI',5,0.12,'No'),
('finance','2.10','Are project milestones monitored against billing milestones?','AR, Billing & Collections','Contract-to-Billing Controls','Project and billing tracker',5,0.12,'Yes'),
('finance','2.11','Is there a formal handoff from Sales to Operations to Finance?','AR, Billing & Collections','Contract-to-Billing Controls','Workflow and handoff checklist',5,0.12,'No'),
('finance','2.12','Can Finance see which completed milestones are ready for billing?','AR, Billing & Collections','Contract-to-Billing Controls','Ready-to-bill tracker',5,0.12,'Yes'),
('finance','2.13','Are invoices prepared immediately after billable milestones are completed?','AR, Billing & Collections','Billing Efficiency','Milestone completion versus invoice dates',5,0.12,'No'),
('finance','2.14','Is the average number of days from acceptance to invoice measured?','AR, Billing & Collections','Billing Efficiency','Billing-cycle KPI',5,0.12,'No'),
('finance','2.15','Are required supporting documents identified before billing?','AR, Billing & Collections','Billing Efficiency','Billing checklist',5,0.12,'No'),
('finance','2.16','Are invoices reviewed for completeness before submission?','AR, Billing & Collections','Billing Efficiency','Invoice review control',5,0.12,'No'),
('finance','2.17','Is customer receipt or acknowledgment of billing documented?','AR, Billing & Collections','Billing Efficiency','Receiving copy or system acknowledgment',5,0.12,'No'),
('finance','2.18','Are rejected or returned billings tracked with reason and resolution owner?','AR, Billing & Collections','Billing Efficiency','Billing rejection tracker',5,0.12,'No'),
('finance','2.19','Are government-specific documentary requirements known before delivery?','AR, Billing & Collections','Government Project Billing','Government billing checklist',5,0.12,'No'),
('finance','2.20','Are inspection and acceptance documents proactively secured?','AR, Billing & Collections','Government Project Billing','IAR and acceptance documents',5,0.12,'Yes'),
('finance','2.21','Are government processing dependencies identified by project?','AR, Billing & Collections','Government Project Billing','Process map and dependency register',4,0.12,'No'),
('finance','2.22','Are delays caused by missing UNICENTER documentation separately tracked?','AR, Billing & Collections','Government Project Billing','Delay root-cause analysis',5,0.12,'No'),
('finance','2.23','Are retention amounts and retention release dates tracked?','AR, Billing & Collections','Government Project Billing','Retention schedule',5,0.12,'No'),
('finance','2.24','Are performance bonds, warranties and their release dates tracked?','AR, Billing & Collections','Government Project Billing','Bond and warranty register',5,0.12,'No'),
('finance','2.25','Does every overdue receivable have an assigned collection owner?','AR, Billing & Collections','Collection Management','Collection tracker',5,0.12,'Yes'),
('finance','2.26','Does every major receivable have a documented next action?','AR, Billing & Collections','Collection Management','Collection action log',5,0.12,'No'),
('finance','2.27','Is an expected collection date maintained for major invoices?','AR, Billing & Collections','Collection Management','Cash collection forecast',5,0.12,'Yes'),
('finance','2.28','Are collection commitments from customers documented?','AR, Billing & Collections','Collection Management','Collection notes and customer commitments',5,0.12,'No'),
('finance','2.29','Are overdue accounts escalated based on predefined aging thresholds?','AR, Billing & Collections','Collection Management','Escalation policy',5,0.12,'No'),
('finance','2.30','Are Sales and Account Managers accountable for collection support—not Finance alone?','AR, Billing & Collections','Collection Management','RACI and KPI scorecards',5,0.12,'No'),
('finance','2.31','Are top overdue accounts reviewed weekly by management?','AR, Billing & Collections','Collection Management','AR War Room minutes and action log',5,0.12,'Yes'),
('finance','2.32','Is DSO (Days Sales Outstanding) calculated and monitored?','AR, Billing & Collections','AR Risk & Collection Quality','DSO dashboard',5,0.12,'No'),
('finance','2.33','Is the percentage of AR >90 days monitored?','AR, Billing & Collections','AR Risk & Collection Quality','AR KPI report',5,0.12,'No'),
('finance','2.34','Is the percentage of AR >180 days monitored?','AR, Billing & Collections','AR Risk & Collection Quality','AR KPI report',5,0.12,'No'),
('finance','2.35','Are doubtful accounts formally assessed and provided for?','AR, Billing & Collections','AR Risk & Collection Quality','Provision policy and allowance schedule',4,0.12,'No'),
('finance','2.36','Are long-outstanding balances independently validated?','AR, Billing & Collections','AR Risk & Collection Quality','Customer confirmation or reconciliation',5,0.12,'No'),
('finance','2.37','Are disputed invoices given a root-cause classification?','AR, Billing & Collections','AR Risk & Collection Quality','Dispute analysis',4,0.12,'No'),
('finance','2.38','Is billing forecasted for the next 30, 60 and 90 days?','AR, Billing & Collections','Cash Conversion & Accountability','Billing forecast',5,0.12,'No'),
('finance','2.39','Is collection forecasted for the next 13 weeks?','AR, Billing & Collections','Cash Conversion & Accountability','Collection forecast',5,0.12,'Yes'),
('finance','2.40','Is forecast-versus-actual collection measured?','AR, Billing & Collections','Cash Conversion & Accountability','Collection variance report',5,0.12,'No'),
('finance','2.41','Is AR performance incorporated into management KPIs?','AR, Billing & Collections','Cash Conversion & Accountability','Management KPI scorecard',4,0.12,'No'),
('finance','2.42','Is project closure dependent on completion of billing documentation?','AR, Billing & Collections','Cash Conversion & Accountability','Project closeout process',5,0.12,'No'),
('finance','2.43','Does management know the amount of unbilled completed work?','AR, Billing & Collections','Cash Conversion & Accountability','Unbilled revenue and work-in-progress report',5,0.12,'Yes'),
('finance','2.44','Does management know how much cash is trapped because of internal documentation or process delays?','AR, Billing & Collections','Cash Conversion & Accountability','Cash conversion root-cause report',5,0.12,'No'),
('procurement','3.1','Is there an approved end-to-end procurement policy covering requisition, sourcing, approval, receiving, payment, exceptions and record retention?','Procurement & Vendor Management','Governance & Authority','Approved policy; revision history; employee acknowledgment',5,0.1,'No'),
('procurement','3.2','Are procurement approval limits and signing authorities formally documented by transaction type and amount?','Procurement & Vendor Management','Governance & Authority','Delegation of Authority; system approval matrix',5,0.1,'Yes'),
('procurement','3.3','Are requisitioning, sourcing, approval, receiving, inventory recording and payment segregated among different people?','Procurement & Vendor Management','Governance & Authority','Role matrix; user-access listing; sampled transactions',5,0.1,'Yes'),
('procurement','3.4','Are emergency, sole-source and direct purchases narrowly defined, justified and independently approved?','Procurement & Vendor Management','Governance & Authority','Exception policy; emergency purchase log; approvals',5,0.1,'No'),
('procurement','3.5','Are procurement KPIs, exceptions and fraud red flags reviewed regularly by management?','Procurement & Vendor Management','Governance & Authority','Dashboard; exception report; review minutes',4,0.1,'No'),
('procurement','3.6','Is there a confidential, evidence-preserving protocol for suspected theft, collusion, kickbacks or procurement fraud?','Procurement & Vendor Management','Governance & Authority','Whistleblowing channel; investigation protocol; case register; access controls',5,0.1,'Yes'),
('procurement','3.7','Are purchases linked to an approved budget, project cost sheet, bill of materials or operating plan?','Procurement & Vendor Management','Planning & Requisition','Budget; project costing; approved BOM; PR samples',5,0.1,'No'),
('procurement','3.8','Are purchase requisitions uniquely numbered or system-generated and fully traceable?','Procurement & Vendor Management','Planning & Requisition','PR register; system sequence; cancellation log',5,0.1,'No'),
('procurement','3.9','Does every requisition state the business need, specification, quantity, budget, required date and requesting owner?','Procurement & Vendor Management','Planning & Requisition','Completed PR samples; required-field controls',4,0.1,'No'),
('procurement','3.10','Is a requester prevented from approving their own purchase?','Procurement & Vendor Management','Planning & Requisition','Workflow configuration; sampled approvals',5,0.1,'Yes'),
('procurement','3.11','Is available inventory, committed stock and open purchase orders checked before a new purchase is approved?','Procurement & Vendor Management','Planning & Requisition','System availability check; PR review evidence; duplicate demand report',5,0.1,'Yes'),
('procurement','3.12','Are repeat, duplicate, unusually urgent or potentially split requisitions automatically or manually flagged?','Procurement & Vendor Management','Planning & Requisition','Exception analytics; PR pattern review',5,0.1,'No'),
('procurement','3.13','Are at least three genuine and comparable quotations obtained when policy thresholds require competition?','Procurement & Vendor Management','Sourcing & Price Integrity','Quotation packets; threshold policy; vendor correspondence',5,0.1,'Yes'),
('procurement','3.14','Are quotations received directly from vendors through controlled channels rather than routed through the requester?','Procurement & Vendor Management','Sourcing & Price Integrity','Procurement mailbox; portal logs; original vendor emails',5,0.1,'Yes'),
('procurement','3.15','Are quotation dates, submission times and versions protected from alteration after receipt?','Procurement & Vendor Management','Sourcing & Price Integrity','Email timestamps; portal audit trail; version history',4,0.1,'No'),
('procurement','3.16','Is vendor selection documented against price, specification, delivery, warranty, credit terms and performance?','Procurement & Vendor Management','Sourcing & Price Integrity','Bid comparison; evaluation criteria; award recommendation',5,0.1,'No'),
('procurement','3.17','Are quoted prices independently benchmarked against market, prior purchases or alternative suppliers?','Procurement & Vendor Management','Sourcing & Price Integrity','Price history; benchmark evidence; variance approval',5,0.1,'No'),
('procurement','3.18','Are suspiciously identical quotations, sequential documents, common contact details or coordinated bids investigated?','Procurement & Vendor Management','Sourcing & Price Integrity','Red-flag review; metadata; vendor contact validation',5,0.1,'Yes'),
('procurement','3.19','Are post-award changes in price, quantity, brand, specification or delivery independently reviewed and approved?','Procurement & Vendor Management','Sourcing & Price Integrity','Change orders; revised comparison; approval trail',5,0.1,'No'),
('procurement','3.20','Are vendors accredited using verified legal name, address, tax registration, ownership, contacts and actual operating capacity?','Procurement & Vendor Management','Vendor Integrity & Conflicts','Vendor accreditation file; registration checks; site validation',5,0.1,'Yes'),
('procurement','3.21','Are beneficial owners and related-party links checked against owners, employees, approvers and their immediate families?','Procurement & Vendor Management','Vendor Integrity & Conflicts','Beneficial ownership declaration; related-party screening',5,0.1,'Yes'),
('procurement','3.22','Do employees and decision-makers submit annual and transaction-specific conflict-of-interest declarations?','Procurement & Vendor Management','Vendor Integrity & Conflicts','Signed declarations; recusal records; annual refresh log',5,0.1,'Yes'),
('procurement','3.23','Are gifts, commissions, rebates, personal favors and supplier-sponsored benefits governed and disclosed?','Procurement & Vendor Management','Vendor Integrity & Conflicts','Gifts policy; disclosure register; employee acknowledgment',5,0.1,'No'),
('procurement','3.24','Are vendor bank-account additions or changes independently verified using a known contact before payment?','Procurement & Vendor Management','Vendor Integrity & Conflicts','Callback record; master-data change log; dual approval',5,0.1,'Yes'),
('procurement','3.25','Are inactive, one-time, newly created and unusually high-spend vendors subject to enhanced review?','Procurement & Vendor Management','Vendor Integrity & Conflicts','Vendor exception report; approval evidence; spend analysis',4,0.1,'No'),
('procurement','3.26','Is an approved purchase order issued before any commitment, delivery or supplier work begins?','Procurement & Vendor Management','PO & Approval Integrity','PO date versus order, delivery and invoice dates',5,0.1,'Yes'),
('procurement','3.27','Are purchase orders uniquely numbered, sequentially controlled and traceable to the requisition and award?','Procurement & Vendor Management','PO & Approval Integrity','PO register; system audit trail; cancelled PO log',5,0.1,'No'),
('procurement','3.28','Are PO approvals enforced by amount, category and exception type with a reliable digital or signed trail?','Procurement & Vendor Management','PO & Approval Integrity','Workflow configuration; approval evidence',5,0.1,'No'),
('procurement','3.29','Are split purchase orders, repeated same-day awards and amounts just below approval thresholds detected?','Procurement & Vendor Management','PO & Approval Integrity','Threshold analytics; vendor/date/requester pattern review',5,0.1,'Yes'),
('procurement','3.30','Are PO amendments, cancellations and quantity or price overrides independently approved and logged?','Procurement & Vendor Management','PO & Approval Integrity','PO revision history; override report; approvals',5,0.1,'No'),
('procurement','3.31','Are blank, unsigned, backdated or retroactively created purchase orders prohibited and monitored?','Procurement & Vendor Management','PO & Approval Integrity','PO audit report; date sequence tests; exception register',5,0.1,'Yes'),
('procurement','3.32','Is receiving performed by a person independent of the buyer, requester and payment approver?','Procurement & Vendor Management','Receiving & Three-Way Match','Role assignments; receiving samples; access rights',5,0.1,'Yes'),
('procurement','3.33','Do receiving reports record actual count, serial number, condition, date, location and receiver signature?','Procurement & Vendor Management','Receiving & Three-Way Match','Receiving report samples; serial register; photos',5,0.1,'Yes'),
('procurement','3.34','Are direct-to-project-site deliveries independently witnessed and supported by time/location-stamped evidence?','Procurement & Vendor Management','Receiving & Three-Way Match','Site receiving report; photos; delivery receipt; witness acknowledgment',5,0.1,'Yes'),
('procurement','3.35','Is a complete three-way match—PO, receiving report and supplier invoice—required before payment?','Procurement & Vendor Management','Receiving & Three-Way Match','AP control; matched document packet; exception approvals',5,0.1,'Yes'),
('procurement','3.36','Are shortages, over-deliveries, substitutions, damages and rejected items logged and resolved before payment?','Procurement & Vendor Management','Receiving & Three-Way Match','Receiving discrepancy log; debit notes; resolution evidence',5,0.1,'No'),
('procurement','3.37','Does Accounts Payable reject duplicate, unmatched, altered or unsupported invoices?','Procurement & Vendor Management','Payment & Vendor Reconciliation','AP exception log; duplicate controls; invoice samples',5,0.1,'Yes'),
('procurement','3.38','Are vendor statements reconciled periodically to POs, receipts, invoices, advances and payments?','Procurement & Vendor Management','Payment & Vendor Reconciliation','Vendor reconciliations; supplier confirmations',4,0.1,'No'),
('procurement','3.39','Are duplicate invoices, duplicate payments, unusual credits and repeated round-sum payments detected and investigated?','Procurement & Vendor Management','Payment & Vendor Reconciliation','Duplicate-payment analytics; credit-note review; case evidence',5,0.1,'Yes'),
('procurement','3.40','Is procurement spend analyzed for concentration, price variance, rush orders, overrides, weekend activity and employee-vendor patterns?','Procurement & Vendor Management','Payment & Vendor Reconciliation','Spend analytics; red-flag dashboard; management actions',5,0.1,'Yes'),
('procurement','4.1','Is there an approved inventory and asset policy defining ownership, custody, receiving, storage, movement, counting, loss and disposal?','Inventory & Asset Management','Governance & Master Data','Approved policy; role matrix; employee acknowledgment',5,0.08,'No'),
('procurement','4.2','Does each stock item have one controlled item code, description, unit of measure, category and status?','Inventory & Asset Management','Governance & Master Data','Item master; duplicate-item report; change log',5,0.08,'No'),
('procurement','4.3','Are warehouses, cages, project sites, vehicles, shelves and bins represented by controlled inventory locations?','Inventory & Asset Management','Governance & Master Data','Location master; warehouse map; bin listing',5,0.08,'No'),
('procurement','4.4','Is one system of record used for on-hand, committed, issued, returned, damaged and available inventory?','Inventory & Asset Management','Governance & Master Data','Inventory system; spreadsheet inventory; reconciliation',5,0.08,'Yes'),
('procurement','4.5','Are high-value, portable and theft-prone items tracked by serial number, asset tag or unique identifier?','Inventory & Asset Management','Governance & Master Data','Serial register; asset tags; physical sample',5,0.08,'Yes'),
('procurement','4.6','Are custodians prevented from approving their own adjustments, write-offs, transfers or disposals?','Inventory & Asset Management','Governance & Master Data','Access matrix; workflow; adjustment samples',5,0.08,'Yes'),
('procurement','4.7','Are deliveries physically counted and inspected by a receiver independent of procurement and the requester?','Inventory & Asset Management','Receiving & Recording','Receiving assignments; count sheets; sampled deliveries',5,0.08,'Yes'),
('procurement','4.8','Is the receiving report matched to the approved PO before inventory is posted?','Inventory & Asset Management','Receiving & Recording','PO and receiving records; system control',5,0.08,'Yes'),
('procurement','4.9','Are serial numbers, model, batch, warranty and condition captured at the point of receipt?','Inventory & Asset Management','Receiving & Recording','Receiving report; serial/warranty register',5,0.08,'No'),
('procurement','4.10','Are delivery discrepancies, substitutions and damage documented with photos and supplier acknowledgment?','Inventory & Asset Management','Receiving & Recording','Discrepancy report; photos; supplier correspondence',5,0.08,'No'),
('procurement','4.11','Are direct-to-project-site deliveries recorded in inventory and independently acknowledged before use or installation?','Inventory & Asset Management','Receiving & Recording','Site receiving report; inventory posting; project acknowledgment',5,0.08,'Yes'),
('procurement','4.12','Are unrecorded, late-posted or receiving-without-PO transactions detected and escalated?','Inventory & Asset Management','Receiving & Recording','Receiving exception report; cut-off testing; incident log',5,0.08,'No'),
('procurement','4.13','Is warehouse access restricted to authorized personnel based on job need?','Inventory & Asset Management','Warehouse Security','Access list; badges/keys; observed practice',5,0.08,'Yes'),
('procurement','4.14','Are keys, access cards and entry/exit logs controlled, reviewed and promptly revoked when roles change?','Inventory & Asset Management','Warehouse Security','Key register; access logs; leaver/change records',5,0.08,'Yes'),
('procurement','4.15','Does CCTV cover receiving, storage, dispatch and exit points, with footage retained and access restricted?','Inventory & Asset Management','Warehouse Security','Camera map; footage sample; retention setting; access log',5,0.08,'Yes'),
('procurement','4.16','Are high-value and theft-prone items stored in locked cages or controlled zones with tamper evidence?','Inventory & Asset Management','Warehouse Security','Physical inspection; cage/access log; seal register',5,0.08,'Yes'),
('procurement','4.17','Are shelves and bins clearly labeled and arranged to make unauthorized removal or concealment visible?','Inventory & Asset Management','Warehouse Security','Warehouse observation; location labels; stock layout',4,0.08,'No'),
('procurement','4.18','Are after-hours, weekend and emergency stock movements specifically authorized and reviewed?','Inventory & Asset Management','Warehouse Security','Movement log; security log; approval evidence',5,0.08,'Yes'),
('procurement','4.19','Are bags, personal items, scrap, cartons and vehicle movements controlled at warehouse exit points?','Inventory & Asset Management','Warehouse Security','Exit-control procedure; gate pass; security inspection log',5,0.08,'Yes'),
('procurement','4.20','Is inventory issued only against an approved request, work order, project BOM or service ticket?','Inventory & Asset Management','Issue, Transfer & Return','Approved issue documents; BOM/work-order match',5,0.08,'Yes'),
('procurement','4.21','Does every issue record item, quantity, serial number, project, issuer, recipient, date and destination?','Inventory & Asset Management','Issue, Transfer & Return','Stock issue slips; digital transaction log; signatures',5,0.08,'Yes'),
('procurement','4.22','Are transfers between warehouse, vehicle and project locations acknowledged by both sender and receiver?','Inventory & Asset Management','Issue, Transfer & Return','Transfer documents; paired acknowledgments; in-transit aging',5,0.08,'Yes'),
('procurement','4.23','Are unused or returned items promptly inspected, re-recorded and placed in the correct condition/location status?','Inventory & Asset Management','Issue, Transfer & Return','Return slips; inspection result; system posting date',5,0.08,'No'),
('procurement','4.24','Does project closeout reconcile items purchased, received, issued, installed, returned, lost and remaining by serial number where applicable?','Inventory & Asset Management','Issue, Transfer & Return','Project inventory reconciliation; closeout checklist',5,0.08,'Yes'),
('procurement','4.25','Are tools, test equipment, demo units and loaned devices assigned to named custodians with return dates?','Inventory & Asset Management','Issue, Transfer & Return','Custody forms; tool register; overdue-item report',5,0.08,'No'),
('procurement','4.26','Are consumable usage norms or reasonableness checks used to detect unusual consumption by project, team or employee?','Inventory & Asset Management','Issue, Transfer & Return','Usage standards; variance report; investigation records',4,0.08,'No'),
('procurement','4.27','Are negative inventory, backdated postings and manual stock adjustments blocked or independently approved with evidence?','Inventory & Asset Management','Issue, Transfer & Return','System controls; adjustment log; audit trail',5,0.08,'Yes'),
('procurement','4.28','Are cycle counts scheduled by ABC value, theft risk, movement volume and prior variance history?','Inventory & Asset Management','Counts & Reconciliation','Cycle-count plan; ABC/risk classification',5,0.08,'No'),
('procurement','4.29','Are surprise counts performed by personnel independent of warehouse custody?','Inventory & Asset Management','Counts & Reconciliation','Surprise-count reports; independent sign-off',5,0.08,'Yes'),
('procurement','4.30','Is a complete wall-to-wall physical inventory conducted at least annually with controlled count sheets?','Inventory & Asset Management','Counts & Reconciliation','Annual count instructions; sheets; sign-offs',5,0.08,'No'),
('procurement','4.31','Are book-to-physical and physical-to-book tests completed by item, location and serial number?','Inventory & Asset Management','Counts & Reconciliation','Count reconciliation; serial-level test; exception list',5,0.08,'Yes'),
('procurement','4.32','Are all variances quantified, aged, root-caused and approved before adjustment?','Inventory & Asset Management','Counts & Reconciliation','Variance register; investigation; adjustment approval',5,0.08,'Yes'),
('procurement','4.33','Are repeated shortages analyzed by item, custodian, shift, project, location, vendor and transaction type?','Inventory & Asset Management','Counts & Reconciliation','Trend analytics; heatmap; corrective actions',5,0.08,'Yes'),
('procurement','4.34','Does management reconcile procurement, receipts, issues, returns, write-offs and ending inventory as one continuous flow?','Inventory & Asset Management','Counts & Reconciliation','Inventory roll-forward; purchase-to-stock reconciliation',5,0.08,'Yes'),
('procurement','4.35','Is there a complete fixed-asset and controlled-equipment register with tag, serial, custodian, location, cost and status?','Inventory & Asset Management','Assets & Custody','Asset register; accounting reconciliation; physical sample',5,0.08,'Yes'),
('procurement','4.36','Are laptops, devices, tools, vehicles and other portable assets issued through signed accountability forms?','Inventory & Asset Management','Assets & Custody','Accountability forms; HR/asset records; sample verification',5,0.08,'Yes'),
('procurement','4.37','Are assets physically verified periodically and upon employee transfer, resignation or project closure?','Inventory & Asset Management','Assets & Custody','Verification reports; clearance process; exception log',5,0.08,'No'),
('procurement','4.38','Are defective, returned, RMA, quarantine and scrap items physically segregated and tracked until final resolution?','Inventory & Asset Management','Loss, RMA & Disposal','RMA register; quarantine area; supplier credits; aging',5,0.08,'No'),
('procurement','4.39','Are disposals, scrap sales and write-offs independently approved, witnessed, documented and reconciled to proceeds?','Inventory & Asset Management','Loss, RMA & Disposal','Disposal approval; witness record; photos; sales receipt',5,0.08,'Yes'),
('procurement','4.40','Are shortages, loss, damage and suspected theft immediately reported, evidence preserved, exposure quantified and investigated with due process?','Inventory & Asset Management','Loss, RMA & Disposal','Incident report; CCTV/access/system logs; loss estimate; investigation and recovery actions',5,0.08,'Yes')
on conflict(type,code) do update set
  title=excluded.title,
  domain=excluded.domain,
  area=excluded.area,
  evidence_check=excluded.evidence_check,
  target_rating=excluded.target_rating,
  domain_weight=excluded.domain_weight,
  critical_control=excluded.critical_control;
