create table if not exists public.ar_receivables (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  project_name text not null default '',
  contract_amount numeric(15,2) not null default 0 check (contract_amount >= 0),
  billing_amount numeric(15,2) check (billing_amount >= 0),
  billing_submission_date date,
  invoice_number text not null default '',
  invoice_date date,
  due_date date,
  amount_collected numeric(15,2) not null default 0 check (amount_collected >= 0),
  closed_date date,
  status text not null default 'Submitted / Under Review' check (status in (
    'Submitted / Under Review','For Correction','Approved / For Processing',
    'For Check Preparation','Check Ready','Partially Paid','Disputed','On Hold','Paid / Closed'
  )),
  last_follow_up_date date,
  next_follow_up_date date,
  promise_to_pay_date date,
  expected_collection_amount numeric(15,2) not null default 0 check (expected_collection_amount >= 0),
  priority text not null default 'Medium' check (priority in ('Critical','High','Medium','Low')),
  responsible_person text not null default '',
  customer_contact text not null default '',
  next_action text not null default '',
  escalation_level text not null default 'None' check (escalation_level in ('None','Supervisor','Management','Executive')),
  issues text not null default '',
  updated_by uuid references auth.users(id),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_ar_receivables_status on public.ar_receivables(status);
create index if not exists idx_ar_receivables_submission on public.ar_receivables(billing_submission_date);
create index if not exists idx_ar_receivables_follow_up on public.ar_receivables(next_follow_up_date);
create index if not exists idx_ar_receivables_promise on public.ar_receivables(promise_to_pay_date);

create or replace function public.set_ar_receivable_audit() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  new.updated_at=now();
  new.updated_by=auth.uid();
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(
    auth.uid(),coalesce(auth.jwt()->>'email',''),
    case when tg_op='INSERT' then 'Created' else 'Updated' end,
    'ar_daily',coalesce(nullif(new.invoice_number,''),new.customer_name),to_jsonb(new)
  );
  return new;
end;
$$;

drop trigger if exists audit_ar_receivable on public.ar_receivables;
create trigger audit_ar_receivable before insert or update on public.ar_receivables
for each row execute function public.set_ar_receivable_audit();

alter table public.ar_receivables enable row level security;
drop policy if exists "authenticated read ar receivables" on public.ar_receivables;
create policy "authenticated read ar receivables" on public.ar_receivables for select to authenticated
using(public.current_user_role() is not null);
drop policy if exists "editors manage ar receivables" on public.ar_receivables;
create policy "editors manage ar receivables" on public.ar_receivables for all to authenticated
using(public.current_user_role() in('Admin','Editor'))
with check(public.current_user_role() in('Admin','Editor'));

