create table if not exists public.ar_payments (
  id bigint generated by default as identity primary key,
  receivable_id bigint not null references public.ar_receivables(id) on delete cascade,
  payment_date date not null default current_date,
  amount numeric(15,2) not null check (amount > 0),
  or_number text,
  payment_method text not null default 'Bank Transfer' check (payment_method in ('Cash','Check','Bank Transfer','GCash / Maya','Other')),
  reference_number text not null default '',
  remarks text not null default '',
  created_by uuid references auth.users(id),
  created_by_email text not null default '',
  created_at timestamptz not null default now()
);

create unique index if not exists uq_ar_payments_or_number
on public.ar_payments(lower(or_number)) where nullif(trim(or_number),'') is not null;
create index if not exists idx_ar_payments_receivable on public.ar_payments(receivable_id,payment_date desc);

insert into public.ar_payments(receivable_id,payment_date,amount,payment_method,remarks,created_by,created_by_email,created_at)
select id,coalesce(closed_date,updated_at::date),amount_collected,'Other','Opening balance imported before payment-ledger activation',updated_by,'',updated_at
from public.ar_receivables r
where amount_collected > 0
and not exists(select 1 from public.ar_payments p where p.receivable_id=r.id);

alter table public.ar_payments enable row level security;
drop policy if exists "authenticated read ar payments" on public.ar_payments;
create policy "authenticated read ar payments" on public.ar_payments for select to authenticated
using(public.current_user_role() is not null);
drop policy if exists "editors insert ar payments" on public.ar_payments;
create policy "editors insert ar payments" on public.ar_payments for insert to authenticated
with check(public.current_user_role() in('Admin','Editor'));

create or replace function public.record_ar_payment(
  p_receivable_id bigint,
  p_payment_date date,
  p_amount numeric,
  p_or_number text,
  p_payment_method text,
  p_reference_number text default '',
  p_remarks text default ''
) returns public.ar_payments
language plpgsql security definer set search_path=public as $$
declare
  v_ar public.ar_receivables;
  v_payment public.ar_payments;
  v_or text:=nullif(trim(p_or_number),'');
begin
  if public.current_user_role() not in ('Admin','Editor') then
    raise exception 'You have view-only access.';
  end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Payment amount must be greater than zero.'; end if;
  if p_payment_date is null then raise exception 'Payment date is required.'; end if;
  if v_or is null then raise exception 'OR number is required.'; end if;

  select * into v_ar from public.ar_receivables where id=p_receivable_id for update;
  if not found then raise exception 'AR record not found.'; end if;
  if v_ar.billing_amount is null then raise exception 'Billing amount is required before recording payment.'; end if;
  if p_amount > v_ar.billing_amount-v_ar.amount_collected then
    raise exception 'Payment exceeds the outstanding collectible of %.',to_char(v_ar.billing_amount-v_ar.amount_collected,'FM999,999,999,990.00');
  end if;
  if exists(select 1 from public.ar_payments where lower(or_number)=lower(v_or)) then
    raise exception 'OR number % has already been used.',v_or;
  end if;

  insert into public.ar_payments(receivable_id,payment_date,amount,or_number,payment_method,reference_number,remarks,created_by,created_by_email)
  values(p_receivable_id,p_payment_date,p_amount,v_or,p_payment_method,coalesce(p_reference_number,''),coalesce(p_remarks,''),auth.uid(),coalesce(auth.jwt()->>'email',''))
  returning * into v_payment;

  update public.ar_receivables set
    amount_collected=amount_collected+p_amount,
    status=case when amount_collected+p_amount>=billing_amount then 'Paid / Closed' when amount_collected+p_amount>0 then 'Partially Paid' else status end,
    closed_date=case when amount_collected+p_amount>=billing_amount then p_payment_date else closed_date end
  where id=p_receivable_id;

  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Payment recorded','ar_payment',v_or,to_jsonb(v_payment));
  return v_payment;
end;
$$;

revoke all on function public.record_ar_payment(bigint,date,numeric,text,text,text,text) from public;
grant execute on function public.record_ar_payment(bigint,date,numeric,text,text,text,text) to authenticated;
