create table if not exists public.presales_stage_templates (
  id bigint generated by default as identity primary key,
  sequence_no integer not null unique,
  stage_name text not null unique,
  accountable_group text not null,
  control_type text not null default 'Internal' check (control_type in ('Internal','Client','Shared')),
  target_days integer,
  timing_anchor text not null default '',
  required_documents text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.presales_projects (
  id bigint generated by default as identity primary key,
  bid_reference text not null unique,
  customer_name text not null,
  project_name text not null,
  opportunity_value numeric(15,2) not null default 0 check (opportunity_value >= 0),
  owner text not null default '',
  priority text not null default 'Medium' check (priority in ('Critical','High','Medium','Low')),
  bid_status text not null default 'Active' check (bid_status in ('Active','On Hold','Won','Lost','Cancelled')),
  start_date date not null default current_date,
  expected_bid_date date,
  current_stage_id bigint references public.presales_stage_templates(id),
  remarks text not null default '',
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.presales_stage_history (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.presales_projects(id) on delete cascade,
  stage_id bigint not null references public.presales_stage_templates(id),
  status text not null default 'Not Started' check (status in ('Not Started','In Progress','Completed','Blocked','Skipped')),
  assigned_to text not null default '',
  planned_start date,
  due_date date,
  actual_start date,
  completed_date date,
  documents_complete boolean not null default false,
  notes text not null default '',
  updated_by uuid references auth.users(id),
  updated_by_email text not null default '',
  updated_at timestamptz not null default now(),
  unique(project_id,stage_id)
);

create index if not exists idx_presales_projects_status on public.presales_projects(bid_status);
create index if not exists idx_presales_stage_history_project on public.presales_stage_history(project_id);
create index if not exists idx_presales_stage_history_due on public.presales_stage_history(due_date);

insert into public.presales_stage_templates(sequence_no,stage_name,accountable_group,control_type,target_days,timing_anchor,required_documents) values
(1,'Referral / Reach-out','CEO / Pre-Sales','Internal',null,'Opportunity identified','Accreditation requirements; client profile'),
(2,'Visit / Survey / Scoping','Pre-Sales / Technical','Shared',null,'Customer engagement confirmed','Site survey; scope notes'),
(3,'Proposal with Specifications','Pre-Sales','Internal',7,'Scoping completed','Technical proposal; specifications'),
(4,'Budgetary Proposal Handoff','Pre-Sales','Shared',null,'Proposal approved internally','Budgetary proposal'),
(5,'TOR / Budget / PhilGEPS','Client','Client',null,'Budgetary proposal received','TOR; PhilGEPS notice'),
(6,'Pre-Bid','Bids Staff','Shared',null,'Bid opportunity published','Pre-bid documents; clarifications'),
(7,'Motion for Reconsideration','Bids Staff','Shared',null,'Disqualification or adverse decision','Motion and supporting documents'),
(8,'Prepare Bid Documents','Bids Staff','Internal',null,'Bid requirements confirmed','Bid documents; distribution certificate'),
(9,'Check Bid Documents','Bids Staff','Internal',null,'Bid package prepared','Completed bid checklist'),
(10,'Bid Opening','Bids Staff / Client','Shared',14,'Pre-bid completed','Bid submission acknowledgement'),
(11,'Post-Qualification','Bids Staff / Client','Shared',10,'Bid opening completed','Post-qualification documents'),
(12,'Issue NOA','Client','Client',10,'Post-qualification passed','Notice of Award'),
(13,'Route NOA to Accounting','Bids Staff','Internal',null,'NOA received','Signed NOA'),
(14,'Request Performance Bond','Accounting','Internal',5,'NOA routed to Accounting','Performance bond request'),
(15,'Return Performance Bond','Accounting','Internal',10,'Bond request submitted','Performance bond'),
(16,'Email Signed NOA / Bond','Bids Staff','Shared',10,'Performance bond received','Signed NOA; performance bond; email proof'),
(17,'Issue Contract / PO','Client','Client',5,'Signed NOA and bond received','Contract or purchase order'),
(18,'Notarize / Legal Completion','Bids Staff','Internal',5,'Contract or PO received','Notarized contract'),
(19,'Issue NTP','Client','Client',5,'Contract completed','Notice to Proceed'),
(20,'PO Routing','Bids Staff','Internal',2,'NTP received','Routing acknowledgement'),
(21,'MR / Components / Purchasing','Purchasing','Internal',null,'PO routed','Material request; component list; supplier documents'),
(22,'Job Order','Technical / Operations','Internal',null,'Requirements confirmed','Job order'),
(23,'Operations Handoff','Technical / Operations','Internal',null,'Materials and job order ready','Deployment plan; checklist'),
(24,'Ongoing Monitoring','Pre-Sales / PMQA','Shared',null,'Operations handoff completed','Monitoring record; completion certificate')
on conflict(sequence_no) do update set stage_name=excluded.stage_name,accountable_group=excluded.accountable_group,control_type=excluded.control_type,target_days=excluded.target_days,timing_anchor=excluded.timing_anchor,required_documents=excluded.required_documents;

create or replace function public.initialize_presales_stages() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.presales_stage_history(project_id,stage_id,status,assigned_to,planned_start,due_date,updated_by,updated_by_email)
  select new.id,t.id,case when t.sequence_no=1 then 'In Progress' else 'Not Started' end,t.accountable_group,
    case when t.sequence_no=1 then new.start_date else null end,
    case when t.sequence_no=1 and t.target_days is not null then new.start_date+t.target_days else null end,
    auth.uid(),coalesce(auth.jwt()->>'email','')
  from public.presales_stage_templates t where t.active=true;
  update public.presales_projects set current_stage_id=(select id from public.presales_stage_templates where sequence_no=1) where id=new.id;
  return new;
end;$$;
drop trigger if exists initialize_presales_project on public.presales_projects;
create trigger initialize_presales_project after insert on public.presales_projects for each row execute function public.initialize_presales_stages();

create or replace function public.set_presales_project_audit() returns trigger language plpgsql security definer set search_path=public as $$
begin
  new.updated_at=now(); new.updated_by=auth.uid();
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),case when tg_op='INSERT' then 'Created' else 'Updated' end,'presales_project',new.bid_reference,to_jsonb(new));
  return new;
end;$$;
drop trigger if exists audit_presales_project on public.presales_projects;
create trigger audit_presales_project before insert or update on public.presales_projects for each row execute function public.set_presales_project_audit();

create or replace function public.update_presales_stage(
  p_history_id bigint,p_status text,p_assigned_to text,p_planned_start date,p_due_date date,
  p_actual_start date,p_completed_date date,p_documents_complete boolean,p_notes text
) returns public.presales_stage_history language plpgsql security definer set search_path=public as $$
declare v_history public.presales_stage_history; v_project public.presales_projects; v_stage public.presales_stage_templates; v_next bigint;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  select * into v_history from public.presales_stage_history where id=p_history_id for update;
  if not found then raise exception 'Stage record not found.'; end if;
  select * into v_stage from public.presales_stage_templates where id=v_history.stage_id;
  update public.presales_stage_history set status=p_status,assigned_to=coalesce(p_assigned_to,''),planned_start=p_planned_start,due_date=p_due_date,
    actual_start=p_actual_start,completed_date=p_completed_date,documents_complete=coalesce(p_documents_complete,false),notes=coalesce(p_notes,''),
    updated_by=auth.uid(),updated_by_email=coalesce(auth.jwt()->>'email',''),updated_at=now() where id=p_history_id returning * into v_history;
  if p_status='Completed' then
    select h.id into v_next from public.presales_stage_history h join public.presales_stage_templates t on t.id=h.stage_id
      where h.project_id=v_history.project_id and t.sequence_no>v_stage.sequence_no and h.status='Not Started' order by t.sequence_no limit 1;
    if v_next is not null then
      update public.presales_stage_history h set status='In Progress',actual_start=coalesce(h.actual_start,current_date),planned_start=coalesce(h.planned_start,current_date),
        due_date=coalesce(h.due_date,current_date+t.target_days),updated_by=auth.uid(),updated_by_email=coalesce(auth.jwt()->>'email',''),updated_at=now()
      from public.presales_stage_templates t where h.id=v_next and t.id=h.stage_id;
      update public.presales_projects set current_stage_id=(select stage_id from public.presales_stage_history where id=v_next) where id=v_history.project_id;
    end if;
  else
    update public.presales_projects set current_stage_id=v_history.stage_id where id=v_history.project_id;
  end if;
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Stage updated','presales_stage',v_stage.stage_name,to_jsonb(v_history));
  return v_history;
end;$$;

alter table public.presales_stage_templates enable row level security;
alter table public.presales_projects enable row level security;
alter table public.presales_stage_history enable row level security;
create policy "authenticated read presales templates" on public.presales_stage_templates for select to authenticated using(public.current_user_role() is not null);
create policy "admins manage presales templates" on public.presales_stage_templates for all to authenticated using(public.current_user_role()='Admin') with check(public.current_user_role()='Admin');
create policy "authenticated read presales projects" on public.presales_projects for select to authenticated using(public.current_user_role() is not null);
create policy "editors manage presales projects" on public.presales_projects for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
create policy "authenticated read presales history" on public.presales_stage_history for select to authenticated using(public.current_user_role() is not null);
create policy "editors manage presales history" on public.presales_stage_history for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
revoke all on function public.update_presales_stage(bigint,text,text,date,date,date,date,boolean,text) from public;
grant execute on function public.update_presales_stage(bigint,text,text,date,date,date,date,boolean,text) to authenticated;
