create table if not exists public.presales_attachments (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.presales_projects(id) on delete cascade,
  history_id bigint not null references public.presales_stage_history(id) on delete cascade,
  file_name text not null,
  storage_path text not null unique,
  mime_type text not null default 'application/octet-stream',
  file_size bigint not null default 0 check (file_size >= 0),
  uploaded_by uuid references auth.users(id),
  uploaded_by_email text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_presales_attachments_history on public.presales_attachments(history_id,created_at desc);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('presales-documents','presales-documents',false,15728640,array[
  'application/pdf','image/jpeg','image/png','image/webp',
  'application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation',
  'text/plain','text/csv'
]) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

alter table public.presales_attachments enable row level security;
drop policy if exists "authenticated read presales attachments" on public.presales_attachments;
create policy "authenticated read presales attachments" on public.presales_attachments for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors insert presales attachments" on public.presales_attachments;
create policy "editors insert presales attachments" on public.presales_attachments for insert to authenticated with check(public.current_user_role() in('Admin','Editor') and uploaded_by=auth.uid());
drop policy if exists "editors delete presales attachments" on public.presales_attachments;
create policy "editors delete presales attachments" on public.presales_attachments for delete to authenticated using(public.current_user_role() in('Admin','Editor'));

drop policy if exists "authenticated read presales files" on storage.objects;
create policy "authenticated read presales files" on storage.objects for select to authenticated using(bucket_id='presales-documents' and public.current_user_role() is not null);
drop policy if exists "editors upload presales files" on storage.objects;
create policy "editors upload presales files" on storage.objects for insert to authenticated with check(bucket_id='presales-documents' and public.current_user_role() in('Admin','Editor'));
drop policy if exists "editors delete presales files" on storage.objects;
create policy "editors delete presales files" on storage.objects for delete to authenticated using(bucket_id='presales-documents' and public.current_user_role() in('Admin','Editor'));
