create table if not exists public.presales_document_requirements (
  id bigint generated by default as identity primary key,
  stage_id bigint not null references public.presales_stage_templates(id) on delete cascade,
  document_name text not null,
  required boolean not null default true,
  sequence_no integer not null default 1,
  active boolean not null default true,
  unique(stage_id,document_name)
);

create table if not exists public.presales_document_checks (
  id bigint generated by default as identity primary key,
  history_id bigint not null references public.presales_stage_history(id) on delete cascade,
  requirement_id bigint not null references public.presales_document_requirements(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  completed_by uuid references auth.users(id),
  unique(history_id,requirement_id)
);

alter table public.presales_stage_history add column if not exists reconsideration_reason text not null default '';
alter table public.presales_stage_history add column if not exists filing_date date;
alter table public.presales_stage_history add column if not exists resolution_date date;
alter table public.presales_stage_history add column if not exists performance_bond_received_date date;
alter table public.presales_stage_history add column if not exists ntp_received_date date;
alter table public.presales_stage_history add column if not exists po_acknowledged_date date;

insert into public.presales_document_requirements(stage_id,document_name,sequence_no)
select t.id,d.name,d.seq from public.presales_stage_templates t join (values
  (1,'Accreditation requirements',1),(1,'Client profile and contacts',2),
  (2,'Site survey or scoping notes',1),(3,'Technical proposal',1),(3,'Approved specifications',2),
  (4,'Budgetary proposal',1),(4,'Proof of customer handoff',2),
  (5,'Terms of Reference',1),(5,'PhilGEPS notice or bid bulletin',2),
  (6,'Pre-bid attendance or minutes',1),(6,'Bid clarifications',2),
  (7,'Motion for Reconsideration',1),(7,'Supporting documents',2),(7,'Customer decision or resolution',3),
  (8,'Bid eligibility documents',1),(8,'Technical bid documents',2),(8,'Financial bid documents',3),(8,'Distribution certificate',4),
  (9,'Completed bid-document checklist',1),(10,'Bid submission acknowledgement',1),(10,'Bid opening result',2),
  (11,'Post-qualification requirements',1),(11,'Post-qualification result',2),
  (12,'Notice of Award',1),(13,'Signed NOA',1),(13,'NOA routing acknowledgement',2),
  (14,'Performance bond request',1),(15,'Performance bond',1),(15,'Bids receipt acknowledgement',2),
  (16,'Signed NOA and bond submission',1),(16,'Email or transmittal proof',2),
  (17,'Contract or Purchase Order',1),(18,'Notarized contract',1),(19,'Notice to Proceed',1),(19,'NTP receipt acknowledgement',2),
  (20,'PO routing record',1),(20,'Department acknowledgement',2),
  (21,'Material Request',1),(21,'Component list',2),(21,'Supplier documents',3),
  (22,'Job Order',1),(23,'Deployment or project plan',1),(23,'Materials and field-worker checklist',2),
  (24,'Monitoring report',1),(24,'Completion or acceptance certificate',2)
) as d(stage_seq,name,seq) on d.stage_seq=t.sequence_no
on conflict(stage_id,document_name) do update set sequence_no=excluded.sequence_no,active=true;

insert into public.presales_document_checks(history_id,requirement_id,completed,completed_at)
select h.id,r.id,h.documents_complete,case when h.documents_complete then h.updated_at else null end
from public.presales_stage_history h join public.presales_document_requirements r on r.stage_id=h.stage_id
on conflict(history_id,requirement_id) do nothing;

create or replace function public.initialize_presales_document_checks() returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.presales_document_checks(history_id,requirement_id)
  select new.id,r.id from public.presales_document_requirements r where r.stage_id=new.stage_id and r.active=true
  on conflict(history_id,requirement_id) do nothing;
  return new;
end;$$;
drop trigger if exists initialize_presales_document_checks on public.presales_stage_history;
create trigger initialize_presales_document_checks after insert on public.presales_stage_history for each row execute function public.initialize_presales_document_checks();

drop function if exists public.update_presales_stage(bigint,text,text,text,date,date,date,date,boolean,text);
create or replace function public.update_presales_stage(
  p_history_id bigint,p_status text,p_outcome text,p_assigned_to text,p_planned_start date,p_due_date date,
  p_actual_start date,p_completed_date date,p_documents_complete boolean,p_notes text,p_completed_requirement_ids bigint[],
  p_reconsideration_reason text,p_filing_date date,p_resolution_date date,p_performance_bond_received_date date,
  p_ntp_received_date date,p_po_acknowledged_date date
) returns public.presales_stage_history language plpgsql security definer set search_path=public as $$
declare v_history public.presales_stage_history;v_stage public.presales_stage_templates;v_project public.presales_projects;v_next bigint;v_outcome text:=coalesce(p_outcome,'Pending');v_missing text;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  select * into v_history from public.presales_stage_history where id=p_history_id for update;if not found then raise exception 'Stage record not found.';end if;
  select * into v_stage from public.presales_stage_templates where id=v_history.stage_id;
  select * into v_project from public.presales_projects where id=v_history.project_id for update;
  if p_status<>'Completed' then v_outcome:='Pending';end if;if p_status='Skipped' then v_outcome:='Not Applicable';end if;
  update public.presales_document_checks c set completed=c.id=any(coalesce(p_completed_requirement_ids,'{}'::bigint[])),completed_at=case when c.id=any(coalesce(p_completed_requirement_ids,'{}'::bigint[])) then coalesce(c.completed_at,now()) else null end,completed_by=case when c.id=any(coalesce(p_completed_requirement_ids,'{}'::bigint[])) then auth.uid() else null end where c.history_id=p_history_id;
  if p_status='Completed' then
    if p_completed_date is null then raise exception 'Completed date is required.';end if;
    select string_agg(r.document_name,', ' order by r.sequence_no) into v_missing from public.presales_document_checks c join public.presales_document_requirements r on r.id=c.requirement_id where c.history_id=p_history_id and r.required and r.active and not c.completed;
    if v_missing is not null then raise exception 'Complete the required document checklist: %',v_missing;end if;
    if exists(select 1 from public.presales_stage_history h join public.presales_stage_templates t on t.id=h.stage_id where h.project_id=v_history.project_id and t.sequence_no<v_stage.sequence_no and h.status not in('Completed','Skipped')) then raise exception 'Complete or skip all preceding stages first.';end if;
  end if;
  if v_stage.sequence_no in(7,10,11) and p_status='Completed' and v_outcome not in('Passed','Failed','Not Applicable') then raise exception 'Select Passed, Failed, or Not Applicable before completing this decision stage.';end if;
  if v_stage.sequence_no=7 and p_status='Completed' and v_outcome<>'Not Applicable' and (nullif(trim(coalesce(p_reconsideration_reason,'')),'') is null or p_filing_date is null or p_resolution_date is null) then raise exception 'Reconsideration reason, filing date, and resolution date are required.';end if;
  if v_stage.sequence_no=15 and p_status='Completed' and p_performance_bond_received_date is null then raise exception 'Performance bond receipt date is required.';end if;
  if v_stage.sequence_no=19 and p_status='Completed' and p_ntp_received_date is null then raise exception 'NTP receipt date is required.';end if;
  if v_stage.sequence_no=20 and p_status='Completed' and p_po_acknowledged_date is null then raise exception 'PO acknowledgement date is required.';end if;
  update public.presales_stage_history set status=p_status,outcome=v_outcome,assigned_to=coalesce(p_assigned_to,''),planned_start=p_planned_start,due_date=p_due_date,actual_start=p_actual_start,completed_date=case when p_status='Completed' then p_completed_date else null end,documents_complete=not exists(select 1 from public.presales_document_checks c join public.presales_document_requirements r on r.id=c.requirement_id where c.history_id=p_history_id and r.required and r.active and not c.completed),notes=coalesce(p_notes,''),auto_skipped=false,reconsideration_reason=coalesce(p_reconsideration_reason,''),filing_date=p_filing_date,resolution_date=p_resolution_date,performance_bond_received_date=p_performance_bond_received_date,ntp_received_date=p_ntp_received_date,po_acknowledged_date=p_po_acknowledged_date,updated_by=auth.uid(),updated_by_email=coalesce(auth.jwt()->>'email',''),updated_at=now() where id=p_history_id returning * into v_history;
  if v_stage.sequence_no in(7,10,11) and v_project.bid_status='Lost' and not(p_status='Completed' and v_outcome='Failed') then update public.presales_projects set bid_status='Active',current_stage_id=v_history.stage_id where id=v_history.project_id;update public.presales_stage_history h set status='Not Started',outcome='Pending',auto_skipped=false,notes=case when h.notes='Automatically skipped after unsuccessful bid outcome.' then '' else h.notes end,updated_by=auth.uid(),updated_by_email=coalesce(auth.jwt()->>'email',''),updated_at=now() from public.presales_stage_templates t where h.project_id=v_history.project_id and h.stage_id=t.id and t.sequence_no>v_stage.sequence_no and h.auto_skipped;end if;
  if v_stage.sequence_no in(7,10,11) and p_status='Completed' and v_outcome='Failed' then update public.presales_projects set bid_status='Lost',current_stage_id=v_history.stage_id where id=v_history.project_id;update public.presales_stage_history h set status='Skipped',outcome='Not Applicable',auto_skipped=true,notes=case when h.notes='' then 'Automatically skipped after unsuccessful bid outcome.' else h.notes end,updated_by=auth.uid(),updated_by_email=coalesce(auth.jwt()->>'email',''),updated_at=now() from public.presales_stage_templates t where h.project_id=v_history.project_id and h.stage_id=t.id and t.sequence_no>v_stage.sequence_no and h.status not in('Completed','Skipped');
  elsif v_stage.sequence_no=12 and p_status='Completed' then update public.presales_projects set bid_status='Won',current_stage_id=v_history.stage_id where id=v_history.project_id;select h.id into v_next from public.presales_stage_history h join public.presales_stage_templates t on t.id=h.stage_id where h.project_id=v_history.project_id and t.sequence_no>v_stage.sequence_no and h.status='Not Started' order by t.sequence_no limit 1;
  elsif p_status='Completed' then select h.id into v_next from public.presales_stage_history h join public.presales_stage_templates t on t.id=h.stage_id where h.project_id=v_history.project_id and t.sequence_no>v_stage.sequence_no and h.status='Not Started' order by t.sequence_no limit 1;else update public.presales_projects set current_stage_id=v_history.stage_id where id=v_history.project_id;end if;
  if v_next is not null then update public.presales_stage_history h set status='In Progress',outcome='Pending',auto_skipped=false,actual_start=coalesce(h.actual_start,current_date),planned_start=coalesce(h.planned_start,current_date),due_date=coalesce(h.due_date,current_date+t.target_days),updated_by=auth.uid(),updated_by_email=coalesce(auth.jwt()->>'email',''),updated_at=now() from public.presales_stage_templates t where h.id=v_next and t.id=h.stage_id;update public.presales_projects set current_stage_id=(select stage_id from public.presales_stage_history where id=v_next) where id=v_history.project_id;end if;
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes) values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Stage updated','presales_stage',v_stage.stage_name,jsonb_build_object('stage',to_jsonb(v_history),'outcome',v_outcome,'bid_status',(select bid_status from public.presales_projects where id=v_history.project_id)));
  return v_history;
end;$$;

alter table public.presales_document_requirements enable row level security;alter table public.presales_document_checks enable row level security;
drop policy if exists "authenticated read presales requirements" on public.presales_document_requirements;
create policy "authenticated read presales requirements" on public.presales_document_requirements for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "admins manage presales requirements" on public.presales_document_requirements;
create policy "admins manage presales requirements" on public.presales_document_requirements for all to authenticated using(public.current_user_role()='Admin') with check(public.current_user_role()='Admin');
drop policy if exists "authenticated read presales checks" on public.presales_document_checks;
create policy "authenticated read presales checks" on public.presales_document_checks for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors manage presales checks" on public.presales_document_checks;
create policy "editors manage presales checks" on public.presales_document_checks for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
revoke all on function public.update_presales_stage(bigint,text,text,text,date,date,date,date,boolean,text,bigint[],text,date,date,date,date,date) from public;
grant execute on function public.update_presales_stage(bigint,text,text,text,date,date,date,date,boolean,text,bigint[],text,date,date,date,date,date) to authenticated;
