alter table public.presales_projects add column if not exists probability integer not null default 20 check (probability between 0 and 100);
alter table public.presales_projects add column if not exists project_type text not null default '';
alter table public.presales_projects add column if not exists business_model text not null default 'Unicenter-Managed';
alter table public.presales_projects add column if not exists primary_contact text not null default '';
alter table public.presales_projects add column if not exists contact_role text not null default '';
alter table public.presales_projects add column if not exists next_action text not null default '';
alter table public.presales_projects add column if not exists next_action_date date;
alter table public.presales_projects add column if not exists opportunity_summary text not null default '';

create table if not exists public.crm_interactions (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.presales_projects(id) on delete cascade,
  interaction_type text not null default 'Client meeting' check (interaction_type in ('Client meeting','Site visit','Workshop','Call','Email','Other')),
  notes text not null,
  interaction_date date not null default current_date,
  next_action text not null default '',
  next_action_date date,
  created_by uuid references auth.users(id),
  created_by_email text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_crm_interactions_project on public.crm_interactions(project_id,interaction_date desc);

alter table public.crm_interactions enable row level security;
drop policy if exists "authenticated read crm interactions" on public.crm_interactions;
create policy "authenticated read crm interactions" on public.crm_interactions for select to authenticated
using(public.current_user_role() is not null);
drop policy if exists "editors manage crm interactions" on public.crm_interactions;
create policy "editors manage crm interactions" on public.crm_interactions for all to authenticated
using(public.current_user_role() in('Admin','Editor'))
with check(public.current_user_role() in('Admin','Editor'));

create or replace function public.set_crm_interaction_audit() returns trigger
language plpgsql security definer set search_path=public as $$
declare v_reference text;
begin
  new.created_by=auth.uid();
  new.created_by_email=coalesce(auth.jwt()->>'email','');
  select bid_reference into v_reference from public.presales_projects where id=new.project_id;
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),new.created_by_email,'Interaction logged','crm_interaction',coalesce(v_reference,new.project_id::text),to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists audit_crm_interaction on public.crm_interactions;
create trigger audit_crm_interaction before insert on public.crm_interactions
for each row execute function public.set_crm_interaction_audit();

