create table if not exists public.inventory_items (
  id bigint generated by default as identity primary key,
  sku text not null unique,
  item_name text not null,
  category text not null default '',
  unit text not null default 'pc',
  reorder_level numeric(15,2) not null default 0 check(reorder_level >= 0),
  active boolean not null default true,
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_material_requests (
  id bigint generated by default as identity primary key,
  request_no text unique,
  project_id bigint not null references public.presales_projects(id) on delete restrict,
  purpose text not null default '',
  needed_by date,
  status text not null default 'Approved' check(status in ('Draft','For Review','Approved','Partially Fulfilled','Fulfilled','Cancelled')),
  requested_by text not null default '',
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_material_request_items (
  id bigint generated by default as identity primary key,
  request_id bigint not null references public.project_material_requests(id) on delete cascade,
  inventory_item_id bigint references public.inventory_items(id) on delete restrict,
  description text not null,
  quantity_required numeric(15,2) not null check(quantity_required > 0),
  quantity_reserved numeric(15,2) not null default 0 check(quantity_reserved >= 0),
  quantity_released numeric(15,2) not null default 0 check(quantity_released >= 0),
  procurement_status text not null default 'For Purchase' check(procurement_status in ('Not Required','For Purchase','Ordered','Partially Received','Received','Cancelled')),
  notes text not null default '',
  created_at timestamptz not null default now(),
  check(quantity_released <= quantity_reserved),
  check(quantity_reserved <= quantity_required)
);

create table if not exists public.procurement_orders (
  id bigint generated by default as identity primary key,
  po_number text not null unique,
  material_request_id bigint not null references public.project_material_requests(id) on delete restrict,
  supplier text not null,
  status text not null default 'Ordered' check(status in ('Draft','For Approval','Approved','Ordered','Partially Received','Received','Cancelled')),
  order_date date not null default current_date,
  expected_delivery date,
  remarks text not null default '',
  created_by uuid references auth.users(id),
  updated_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.procurement_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.procurement_orders(id) on delete cascade,
  request_item_id bigint not null references public.project_material_request_items(id) on delete restrict,
  quantity_ordered numeric(15,2) not null check(quantity_ordered > 0),
  quantity_received numeric(15,2) not null default 0 check(quantity_received >= 0),
  unit_cost numeric(15,2) not null default 0 check(unit_cost >= 0),
  created_at timestamptz not null default now(),
  unique(order_id,request_item_id),
  check(quantity_received <= quantity_ordered)
);

create table if not exists public.inventory_stock_movements (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.inventory_items(id) on delete restrict,
  project_id bigint references public.presales_projects(id) on delete restrict,
  request_item_id bigint references public.project_material_request_items(id) on delete restrict,
  movement_type text not null check(movement_type in ('Receipt','Release','Return','Adjustment In','Adjustment Out')),
  quantity numeric(15,2) not null check(quantity > 0),
  unit_cost numeric(15,2) not null default 0 check(unit_cost >= 0),
  reference text not null default '',
  movement_date date not null default current_date,
  notes text not null default '',
  created_by uuid references auth.users(id),
  created_by_email text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_inventory_movements_item on public.inventory_stock_movements(inventory_item_id,movement_date desc);
create index if not exists idx_inventory_movements_project on public.inventory_stock_movements(project_id);
create index if not exists idx_material_requests_project on public.project_material_requests(project_id,status);
create index if not exists idx_material_request_items_request on public.project_material_request_items(request_id);
create index if not exists idx_procurement_orders_request on public.procurement_orders(material_request_id,status);

create or replace function public.allocate_project_material_request(p_request_id bigint)
returns public.project_material_requests
language plpgsql security definer set search_path=public as $$
declare
  v_request public.project_material_requests;
  v_item public.project_material_request_items;
  v_on_hand numeric;
  v_other_reserved numeric;
  v_outstanding numeric;
  v_allocate numeric;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  select * into v_request from public.project_material_requests where id=p_request_id for update;
  if not found then raise exception 'Material request not found.'; end if;
  if v_request.status='Cancelled' then raise exception 'Cancelled material requests cannot be allocated.'; end if;

  for v_item in select * from public.project_material_request_items where request_id=p_request_id order by id for update loop
    if v_item.inventory_item_id is null then
      update public.project_material_request_items set quantity_reserved=quantity_released,procurement_status='For Purchase' where id=v_item.id;
      continue;
    end if;
    perform pg_advisory_xact_lock(v_item.inventory_item_id);
    select coalesce(sum(case when movement_type in ('Receipt','Return','Adjustment In') then quantity else -quantity end),0)
      into v_on_hand from public.inventory_stock_movements where inventory_item_id=v_item.inventory_item_id;
    select coalesce(sum(i.quantity_reserved-i.quantity_released),0)
      into v_other_reserved
      from public.project_material_request_items i
      join public.project_material_requests r on r.id=i.request_id
      where i.inventory_item_id=v_item.inventory_item_id and i.id<>v_item.id and r.status not in ('Cancelled','Fulfilled');
    v_outstanding:=greatest(0,v_item.quantity_required-v_item.quantity_released);
    v_allocate:=least(v_outstanding,greatest(0,v_on_hand-v_other_reserved));
    update public.project_material_request_items set
      quantity_reserved=quantity_released+v_allocate,
      procurement_status=case
        when quantity_released+v_allocate>=quantity_required then 'Not Required'
        when procurement_status in ('Ordered','Partially Received') then procurement_status
        else 'For Purchase'
      end
    where id=v_item.id;
  end loop;

  update public.project_material_requests set
    status=case
      when not exists(select 1 from public.project_material_request_items where request_id=p_request_id and quantity_released<quantity_required) then 'Fulfilled'
      when exists(select 1 from public.project_material_request_items where request_id=p_request_id and quantity_released>0) then 'Partially Fulfilled'
      else 'Approved' end,
    updated_by=auth.uid(),updated_at=now()
  where id=p_request_id returning * into v_request;
  return v_request;
end;$$;

create or replace function public.create_project_material_request(
  p_project_id bigint,p_needed_by date,p_purpose text,p_requested_by text,p_items jsonb
) returns public.project_material_requests
language plpgsql security definer set search_path=public as $$
declare v_request public.project_material_requests;v_line jsonb;v_item public.inventory_items;v_description text;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  if not exists(select 1 from public.presales_projects where id=p_project_id) then raise exception 'CRM project not found.'; end if;
  if jsonb_array_length(coalesce(p_items,'[]'::jsonb))=0 then raise exception 'Add at least one material item.'; end if;
  insert into public.project_material_requests(project_id,purpose,needed_by,requested_by,created_by,updated_by)
  values(p_project_id,coalesce(trim(p_purpose),''),p_needed_by,coalesce(trim(p_requested_by),''),auth.uid(),auth.uid()) returning * into v_request;
  update public.project_material_requests set request_no='MR-'||to_char(current_date,'YYYY')||'-'||lpad(v_request.id::text,5,'0') where id=v_request.id returning * into v_request;
  for v_line in select * from jsonb_array_elements(p_items) loop
    if nullif(v_line->>'inventory_item_id','') is null then raise exception 'Add every requested material to the stock catalog first.'; end if;
    select * into v_item from public.inventory_items where id=(v_line->>'inventory_item_id')::bigint and active=true;
    if not found then raise exception 'One selected inventory item is unavailable.'; end if;
    v_description:=v_item.item_name;
    insert into public.project_material_request_items(request_id,inventory_item_id,description,quantity_required,notes)
    values(v_request.id,nullif(v_line->>'inventory_item_id','')::bigint,v_description,(v_line->>'quantity')::numeric,coalesce(v_line->>'notes',''));
  end loop;
  perform public.allocate_project_material_request(v_request.id);
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Material request created','project_material_request',v_request.request_no,to_jsonb(v_request));
  select * into v_request from public.project_material_requests where id=v_request.id;
  return v_request;
end;$$;

create or replace function public.create_procurement_order(
  p_request_id bigint,p_po_number text,p_supplier text,p_expected_delivery date,p_remarks text
) returns public.procurement_orders
language plpgsql security definer set search_path=public as $$
declare v_order public.procurement_orders;v_count integer;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  if nullif(trim(p_po_number),'') is null then raise exception 'PO number is required.'; end if;
  if nullif(trim(p_supplier),'') is null then raise exception 'Supplier is required.'; end if;
  if not exists(select 1 from public.project_material_requests where id=p_request_id and status<>'Cancelled') then raise exception 'Active material request not found.'; end if;
  insert into public.procurement_orders(po_number,material_request_id,supplier,expected_delivery,remarks,created_by,updated_by)
  values(upper(trim(p_po_number)),p_request_id,trim(p_supplier),p_expected_delivery,coalesce(trim(p_remarks),''),auth.uid(),auth.uid()) returning * into v_order;
  insert into public.procurement_order_items(order_id,request_item_id,quantity_ordered)
  select v_order.id,i.id,i.quantity_required-i.quantity_reserved
  from public.project_material_request_items i
  where i.request_id=p_request_id and i.quantity_required>i.quantity_reserved and i.procurement_status not in ('Ordered','Received','Cancelled');
  get diagnostics v_count=row_count;
  if v_count=0 then raise exception 'This request has no un-ordered shortages.'; end if;
  update public.project_material_request_items set procurement_status='Ordered'
  where id in(select request_item_id from public.procurement_order_items where order_id=v_order.id);
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Purchase order created','procurement_order',v_order.po_number,to_jsonb(v_order));
  return v_order;
end;$$;

create or replace function public.receive_procurement_order(p_order_id bigint,p_reference text,p_received_date date)
returns public.procurement_orders
language plpgsql security definer set search_path=public as $$
declare v_order public.procurement_orders;v_line record;v_item public.project_material_request_items;v_quantity numeric;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  select * into v_order from public.procurement_orders where id=p_order_id for update;
  if not found or v_order.status in ('Received','Cancelled') then raise exception 'Open purchase order not found.'; end if;
  for v_line in select * from public.procurement_order_items where order_id=p_order_id for update loop
    v_quantity:=v_line.quantity_ordered-v_line.quantity_received;
    if v_quantity<=0 then continue; end if;
    select * into v_item from public.project_material_request_items where id=v_line.request_item_id;
    if v_item.inventory_item_id is null then raise exception 'Create an inventory catalog item for % before receiving.',v_item.description; end if;
    insert into public.inventory_stock_movements(inventory_item_id,project_id,request_item_id,movement_type,quantity,unit_cost,reference,movement_date,notes,created_by,created_by_email)
    select v_item.inventory_item_id,r.project_id,v_item.id,'Receipt',v_quantity,v_line.unit_cost,coalesce(nullif(trim(p_reference),''),v_order.po_number),coalesce(p_received_date,current_date),'Procurement receipt',auth.uid(),coalesce(auth.jwt()->>'email','')
    from public.project_material_requests r where r.id=v_item.request_id;
    update public.procurement_order_items set quantity_received=quantity_ordered where id=v_line.id;
    update public.project_material_request_items set procurement_status='Received' where id=v_item.id;
  end loop;
  update public.procurement_orders set status='Received',updated_by=auth.uid(),updated_at=now() where id=p_order_id returning * into v_order;
  perform public.allocate_project_material_request(v_order.material_request_id);
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Purchase order received','procurement_order',v_order.po_number,to_jsonb(v_order));
  return v_order;
end;$$;

create or replace function public.release_project_materials(p_request_id bigint,p_reference text,p_release_date date)
returns public.project_material_requests
language plpgsql security definer set search_path=public as $$
declare v_request public.project_material_requests;v_item public.project_material_request_items;v_quantity numeric;
begin
  if public.current_user_role() not in ('Admin','Editor') then raise exception 'You have view-only access.'; end if;
  select * into v_request from public.project_material_requests where id=p_request_id for update;
  if not found or v_request.status='Cancelled' then raise exception 'Active material request not found.'; end if;
  for v_item in select * from public.project_material_request_items where request_id=p_request_id for update loop
    v_quantity:=v_item.quantity_reserved-v_item.quantity_released;
    if v_quantity<=0 then continue; end if;
    insert into public.inventory_stock_movements(inventory_item_id,project_id,request_item_id,movement_type,quantity,reference,movement_date,notes,created_by,created_by_email)
    values(v_item.inventory_item_id,v_request.project_id,v_item.id,'Release',v_quantity,coalesce(nullif(trim(p_reference),''),v_request.request_no),coalesce(p_release_date,current_date),'Released to project',auth.uid(),coalesce(auth.jwt()->>'email',''));
    update public.project_material_request_items set quantity_released=quantity_released+v_quantity where id=v_item.id;
  end loop;
  perform public.allocate_project_material_request(p_request_id);
  select * into v_request from public.project_material_requests where id=p_request_id;
  insert into public.audit_logs(user_id,user_email,action,record_type,record_code,changes)
  values(auth.uid(),coalesce(auth.jwt()->>'email',''),'Project materials released','project_material_request',v_request.request_no,to_jsonb(v_request));
  return v_request;
end;$$;

alter table public.inventory_items enable row level security;
alter table public.inventory_stock_movements enable row level security;
alter table public.project_material_requests enable row level security;
alter table public.project_material_request_items enable row level security;
alter table public.procurement_orders enable row level security;
alter table public.procurement_order_items enable row level security;

drop policy if exists "authenticated read inventory items" on public.inventory_items;
create policy "authenticated read inventory items" on public.inventory_items for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors manage inventory items" on public.inventory_items;
create policy "editors manage inventory items" on public.inventory_items for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
drop policy if exists "authenticated read stock movements" on public.inventory_stock_movements;
create policy "authenticated read stock movements" on public.inventory_stock_movements for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors insert stock movements" on public.inventory_stock_movements;
create policy "editors insert stock movements" on public.inventory_stock_movements for insert to authenticated with check(public.current_user_role() in('Admin','Editor'));
drop policy if exists "authenticated read material requests" on public.project_material_requests;
create policy "authenticated read material requests" on public.project_material_requests for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors manage material requests" on public.project_material_requests;
create policy "editors manage material requests" on public.project_material_requests for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
drop policy if exists "authenticated read material request items" on public.project_material_request_items;
create policy "authenticated read material request items" on public.project_material_request_items for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors manage material request items" on public.project_material_request_items;
create policy "editors manage material request items" on public.project_material_request_items for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
drop policy if exists "authenticated read procurement orders" on public.procurement_orders;
create policy "authenticated read procurement orders" on public.procurement_orders for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors manage procurement orders" on public.procurement_orders;
create policy "editors manage procurement orders" on public.procurement_orders for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));
drop policy if exists "authenticated read procurement order items" on public.procurement_order_items;
create policy "authenticated read procurement order items" on public.procurement_order_items for select to authenticated using(public.current_user_role() is not null);
drop policy if exists "editors manage procurement order items" on public.procurement_order_items;
create policy "editors manage procurement order items" on public.procurement_order_items for all to authenticated using(public.current_user_role() in('Admin','Editor')) with check(public.current_user_role() in('Admin','Editor'));

revoke all on function public.allocate_project_material_request(bigint) from public;
revoke all on function public.create_project_material_request(bigint,date,text,text,jsonb) from public;
revoke all on function public.create_procurement_order(bigint,text,text,date,text) from public;
revoke all on function public.receive_procurement_order(bigint,text,date) from public;
revoke all on function public.release_project_materials(bigint,text,date) from public;
grant execute on function public.allocate_project_material_request(bigint) to authenticated;
grant execute on function public.create_project_material_request(bigint,date,text,text,jsonb) to authenticated;
grant execute on function public.create_procurement_order(bigint,text,text,date,text) to authenticated;
grant execute on function public.receive_procurement_order(bigint,text,date) to authenticated;
grant execute on function public.release_project_materials(bigint,text,date) to authenticated;
